<?php

declare(strict_types=1);

namespace App\Service;

use App\Container\EntityManagerAwareTrait;
use App\Entity\Station;
use App\Radio\Adapters;
use App\Radio\Backend\Liquidsoap;
use RuntimeException;
use Throwable;

final class AirCheckLiquidsoapRecovery
{
    use EntityManagerAwareTrait;

    private const int LOG_TAIL_BYTES = 16384;
    private const int MAX_REASON_LENGTH = 420;

    public function __construct(
        private readonly Adapters $adapters,
    ) {
    }

    /**
     * If the normal AirCheck restart failed for Liquidsoap, validate the configuration
     * generated by the currently-running AzuraCast code, write it to disk and retry.
     *
     * This deliberately does not perform a Git rollback. Runtime recovery should never
     * mutate application source code; when current code generates an invalid Liquidsoap
     * configuration, the validation error and a short log hint are returned instead.
     *
     * @param array<string, mixed> $result
     * @return array<string, mixed>
     */
    public function recover(Station $station, array $result): array
    {
        $failures = array_values(array_map('strval', (array)($result['failures'] ?? [])));
        $hasBackendFailure = false;

        foreach ($failures as $failure) {
            if (str_starts_with($failure, 'backend:')) {
                $hasBackendFailure = true;
                break;
            }
        }

        if (!$hasBackendFailure) {
            return $result;
        }

        $adapter = $this->adapters->getBackendAdapter($station);
        if (!$adapter instanceof Liquidsoap) {
            return $result;
        }

        try {
            $generatedConfig = $adapter->getCurrentConfiguration($station);
            if ('' === trim($generatedConfig)) {
                throw new RuntimeException('AzuraCast generated an empty Liquidsoap configuration.');
            }

            // Validate before overwriting the on-disk configuration. If recently-added
            // code produces invalid Liquidsoap syntax, this returns the exact parser
            // reason instead of repeatedly trying to start a process that cannot boot.
            $adapter->verifyConfig($generatedConfig);
            $adapter->write($station);
            $adapter->restart($station);

            if (!$adapter->isRunning($station)) {
                throw new RuntimeException('Liquidsoap stopped again immediately after the recovery restart.');
            }

            $failures = array_values(array_filter(
                $failures,
                static fn(string $failure): bool => !str_starts_with($failure, 'backend:')
            ));

            $restarted = array_values(array_unique([
                ...(array)($result['restarted'] ?? []),
                'backend',
            ]));

            $result['restarted'] = $restarted;
            $result['failures'] = $failures;
            $result['liquidsoap_recovery'] = [
                'recovered' => true,
                'reason' => 'Current Liquidsoap configuration validated, was rewritten, and Liquidsoap started successfully.',
            ];
        } catch (Throwable $e) {
            $reason = $this->shortReason($e->getMessage());
            $logHint = $this->getLogHint($adapter, $station);
            if (null !== $logHint && !str_contains($reason, $logHint)) {
                $reason .= ' | liquidsoap.log: ' . $logHint;
            }

            $failures = array_values(array_filter(
                $failures,
                static fn(string $failure): bool => !str_starts_with($failure, 'backend:')
            ));
            $failures[] = 'backend: ' . $reason;

            $result['failures'] = $failures;
            $result['liquidsoap_recovery'] = [
                'recovered' => false,
                'reason' => $reason,
                'suggestion' => $this->suggestFix($reason),
            ];
        }

        $result['healthy'] = [] === (array)($result['restarted'] ?? [])
            && [] === (array)($result['failures'] ?? []);

        $this->syncLatestIntervention($station, $result);

        return $result;
    }

    /** @param array<string, mixed> $result */
    private function syncLatestIntervention(Station $station, array $result): void
    {
        $timestamp = (int)($result['timestamp'] ?? 0);
        if ($timestamp <= 0) {
            return;
        }

        $needsRestartBefore = $station->needs_restart;
        $config = $station->backend_config;
        $history = array_values($config->aircheck_interventions);
        $changed = false;

        foreach ($history as $index => $intervention) {
            if ((int)($intervention['timestamp'] ?? 0) !== $timestamp) {
                continue;
            }

            $history[$index]['services'] = array_values((array)($result['restarted'] ?? []));
            $history[$index]['failures'] = array_values((array)($result['failures'] ?? []));
            $changed = true;
            break;
        }

        if (!$changed) {
            return;
        }

        $config->aircheck_interventions = $history;
        $station->backend_config = $config;
        $station->needs_restart = $needsRestartBefore;
        $this->em->persist($station);
        $this->em->flush();
    }

    private function getLogHint(Liquidsoap $adapter, Station $station): ?string
    {
        $path = $adapter->getLogPath($station);
        if (!is_readable($path)) {
            return null;
        }

        $handle = @fopen($path, 'rb');
        if (false === $handle) {
            return null;
        }

        try {
            if (0 !== fseek($handle, 0, SEEK_END)) {
                return null;
            }

            $size = ftell($handle);
            if (false === $size || $size <= 0) {
                return null;
            }

            $offset = max(0, $size - self::LOG_TAIL_BYTES);
            if (0 !== fseek($handle, $offset, SEEK_SET)) {
                return null;
            }

            $tail = stream_get_contents($handle, self::LOG_TAIL_BYTES);
            if (false === $tail || '' === trim($tail)) {
                return null;
            }
        } finally {
            fclose($handle);
        }

        $lines = preg_split('/\R/', $tail) ?: [];
        $fallback = null;

        foreach (array_reverse($lines) as $line) {
            $line = trim($line);
            if ('' === $line) {
                continue;
            }

            $fallback ??= $line;
            if (preg_match('/\b(error|fatal|exception|invalid|failed|failure|syntax|parse)\b/i', $line)) {
                return $this->shortReason($line);
            }
        }

        return null !== $fallback ? $this->shortReason($fallback) : null;
    }

    private function shortReason(string $reason): string
    {
        $reason = trim((string)preg_replace('/\s+/', ' ', $reason));
        if (mb_strlen($reason) <= self::MAX_REASON_LENGTH) {
            return $reason;
        }

        return mb_substr($reason, 0, self::MAX_REASON_LENGTH - 1) . '…';
    }

    private function suggestFix(string $reason): string
    {
        $lower = strtolower($reason);

        if (str_contains($lower, 'syntax') || str_contains($lower, 'parse') || str_contains($lower, 'invalid')) {
            return 'Review the generated Liquidsoap configuration and the most recent Liquidsoap/config-writer changes.';
        }

        if (str_contains($lower, 'address already in use') || str_contains($lower, 'bind')) {
            return 'Check for a conflicting process or duplicate Liquidsoap/frontend port before retrying.';
        }

        if (str_contains($lower, 'permission denied')) {
            return 'Check station media/config/log file ownership and permissions.';
        }

        if (str_contains($lower, 'no such file') || str_contains($lower, 'not found')) {
            return 'Check referenced media, playlists, custom Liquidsoap includes, and generated file paths.';
        }

        return 'Open the Liquidsoap log/configuration and use the reported startup reason to fix the failing setting or recent configuration change.';
    }
}
