<template>
    <section
        class="card"
        role="region"
        aria-labelledby="hdr_clock_wheel_editor"
    >
        <div class="card-header text-bg-primary d-flex align-items-center gap-3 flex-wrap">
            <button
                type="button"
                class="btn btn-sm btn-light"
                @click="emit('cancel')"
            >
                ← {{ $gettext('All Clock Wheels') }}
            </button>
            <h2
                id="hdr_clock_wheel_editor"
                class="card-title my-0 flex-fill"
            >
                {{ isEditMode ? form.name || $gettext('Edit Clock Wheel') : $gettext('New Clock Wheel') }}
            </h2>
        </div>

        <div
            v-if="error"
            class="alert alert-danger rounded-0 mb-0"
        >
            {{ error }}
        </div>
        <div
            v-if="isDaypartManaged"
            class="alert alert-warning rounded-0 mb-0"
        >
            {{ $gettext('This wheel was generated by a daypart; a daypart re-sync can replace its slots.') }}
        </div>

        <loading
            :loading="isBusy && !loaded"
            lazy
        >
            <div class="card-body">
                <div class="row g-4">
                    <div class="col-lg-4">
                        <div class="d-flex justify-content-center mb-3">
                            <wheel-dial
                                :slots="dialSlots"
                                :size="300"
                                :center-label="form.name || $gettext('New Wheel')"
                                :center-sub="$ngettext('%{n} slot', '%{n} slots', entries.length, {n: String(entries.length)})"
                                :selected-index="selectedIndex"
                                :aria-label="$gettext('Clock wheel preview')"
                                @select="selectRow"
                            />
                        </div>

                        <div class="d-flex flex-wrap justify-content-center gap-3 small mb-3">
                            <span
                                v-for="opt in typeOptions"
                                :key="opt.value"
                                class="d-inline-flex align-items-center gap-1"
                            >
                                <span
                                    class="legend-dot"
                                    :style="{background: clockWheelTypeColor(opt.value)}"
                                />
                                {{ opt.short }}
                            </span>
                        </div>

                        <div class="card bg-body-tertiary">
                            <div class="card-body">
                                <h3 class="h6 mb-3">
                                    {{ $gettext('Hour Distribution') }}
                                </h3>
                                <div
                                    v-for="row in distributionRows"
                                    :key="row.key"
                                    class="mb-2"
                                >
                                    <div class="d-flex justify-content-between small mb-1">
                                        <span>{{ row.label }}</span>
                                        <span class="fw-semibold">{{ row.percent }}%</span>
                                    </div>
                                    <div
                                        class="progress"
                                        style="height: 6px;"
                                    >
                                        <div
                                            class="progress-bar"
                                            :style="{width: row.percent + '%', background: row.color}"
                                        />
                                    </div>
                                </div>
                                <p class="small text-muted mb-0 mt-3">
                                    {{ $gettext('Estimated hour') }}: {{ formatPosition(estimatedLoopSeconds) }}
                                    <span
                                        class="badge ms-1"
                                        :class="layoutValid ? 'text-bg-success' : 'text-bg-warning'"
                                    >
                                        {{ layoutValid ? $gettext('Valid layout') : $gettext('Needs review') }}
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-8">
                        <h3 class="h6">
                            {{ $gettext('Wheel Details') }}
                        </h3>
                        <div class="row g-3 mb-4">
                            <div class="col-md-5">
                                <label
                                    class="form-label"
                                    for="cw_name"
                                >{{ $gettext('Name') }}</label>
                                <input
                                    id="cw_name"
                                    v-model="form.name"
                                    type="text"
                                    class="form-control"
                                    :class="{'is-invalid': submitted && !form.name.trim()}"
                                    required
                                >
                            </div>
                            <div class="col-md-2 col-4">
                                <label
                                    class="form-label"
                                    for="cw_color"
                                >{{ $gettext('Color') }}</label>
                                <input
                                    id="cw_color"
                                    v-model="form.color"
                                    type="color"
                                    class="form-control form-control-color w-100"
                                >
                            </div>
                            <div class="col-md-2 col-8">
                                <label
                                    class="form-label"
                                    for="cw_status"
                                >{{ $gettext('Status') }}</label>
                                <select
                                    id="cw_status"
                                    v-model="form.is_active"
                                    class="form-select"
                                >
                                    <option :value="true">
                                        {{ $gettext('Active') }}
                                    </option>
                                    <option :value="false">
                                        {{ $gettext('Inactive') }}
                                    </option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label
                                    class="form-label"
                                    for="cw_fill"
                                >{{ $gettext('Fill Strategy') }}</label>
                                <select
                                    id="cw_fill"
                                    v-model="form.fill_strategy"
                                    class="form-select"
                                >
                                    <option value="conservative">
                                        {{ $gettext('Conservative') }}
                                    </option>
                                    <option value="aggressive">
                                        {{ $gettext('Aggressive') }}
                                    </option>
                                </select>
                            </div>
                            <div class="col-12 form-text mt-1">
                                {{ $gettext('Conservative skips a slot that does not fit its window; Aggressive picks the shortest track that fits.') }}
                                {{ $gettext('Air times are set on the Schedule page.') }}
                            </div>
                        </div>

                        <div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-2">
                            <h3 class="h6 mb-0">
                                {{ $gettext('Slots') }} ({{ entries.length }})
                            </h3>
                            <div class="d-flex flex-wrap gap-1">
                                <button
                                    v-for="opt in typeOptions"
                                    :key="opt.value"
                                    type="button"
                                    class="btn btn-sm btn-outline-secondary"
                                    @click="addSlot(opt.value)"
                                >
                                    <span
                                        class="legend-dot me-1"
                                        :style="{background: clockWheelTypeColor(opt.value)}"
                                    />
                                    + {{ opt.short }}
                                </button>
                            </div>
                        </div>

                        <div
                            v-if="timelineWarnings.length > 0"
                            class="alert alert-warning py-2 small"
                        >
                            <div
                                v-for="(warn, wi) in timelineWarnings"
                                :key="wi"
                            >
                                {{ formatPosition(entries[warn.index]?.position_seconds ?? 0) }}: {{ warn.message }}
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-sm table-striped align-middle mb-0 slot-table">
                                <thead>
                                    <tr>
                                        <th style="width: 1.5rem;" />
                                        <th>{{ $gettext('Position') }}</th>
                                        <th>{{ $gettext('Type') }}</th>
                                        <th>{{ $gettext('Category') }}</th>
                                        <th>{{ $gettext('Algorithm') }}</th>
                                        <th>{{ $gettext('Max Sec') }}</th>
                                        <th class="text-end">
                                            <span class="visually-hidden">{{ $gettext('Actions') }}</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody ref="$tbody">
                                    <tr v-if="entries.length === 0">
                                        <td
                                            colspan="7"
                                            class="text-center text-muted py-4"
                                        >
                                            {{ $gettext('No slots yet. Use the buttons above to build your hour.') }}
                                        </td>
                                    </tr>
                                    <tr
                                        v-for="(entry, index) in entries"
                                        :key="entryKeys[index]"
                                        :data-entry-index="index"
                                        :class="{'table-active': selectedIndex === index, 'table-warning': rowHasWarning(index)}"
                                        @click="selectedIndex = index"
                                    >
                                        <td class="drag-handle text-muted text-center">
                                            <span
                                                class="type-bar"
                                                :style="{background: clockWheelTypeColor(entry.type)}"
                                            />
                                        </td>
                                        <td style="min-width: 5.5rem;">
                                            <input
                                                :value="formatPosition(entry.position_seconds)"
                                                type="text"
                                                class="form-control form-control-sm"
                                                :aria-label="$gettext('Position (m:s)')"
                                                placeholder="0:00"
                                                @change="onPositionChange(entry, $event)"
                                            >
                                        </td>
                                        <td style="min-width: 7rem;">
                                            <select
                                                v-model="entry.type"
                                                class="form-select form-select-sm"
                                                :aria-label="$gettext('Type')"
                                            >
                                                <option
                                                    v-for="opt in typeOptions"
                                                    :key="opt.value"
                                                    :value="opt.value"
                                                >
                                                    {{ opt.short }}
                                                </option>
                                            </select>
                                        </td>
                                        <td style="min-width: 8rem;">
                                            <select
                                                v-model="entry.category_id"
                                                class="form-select form-select-sm"
                                                :aria-label="$gettext('Category')"
                                            >
                                                <option
                                                    v-for="opt in categoryOptions"
                                                    :key="String(opt.value)"
                                                    :value="opt.value"
                                                >
                                                    {{ opt.text }}
                                                </option>
                                            </select>
                                        </td>
                                        <td style="min-width: 9rem;">
                                            <select
                                                v-model="entry.algorithm"
                                                class="form-select form-select-sm"
                                                :aria-label="$gettext('Algorithm')"
                                            >
                                                <option
                                                    v-for="opt in algorithmOptions"
                                                    :key="opt.value"
                                                    :value="opt.value"
                                                >
                                                    {{ opt.text }}
                                                </option>
                                            </select>
                                        </td>
                                        <td style="min-width: 5.5rem;">
                                            <input
                                                v-model.number="entry.duration_seconds"
                                                type="number"
                                                min="0"
                                                max="3600"
                                                class="form-control form-control-sm"
                                                :aria-label="$gettext('Max seconds')"
                                                :placeholder="$gettext('Auto')"
                                            >
                                        </td>
                                        <td class="text-end text-nowrap">
                                            <button
                                                type="button"
                                                class="btn btn-sm btn-link text-secondary p-1"
                                                :title="$gettext('Duplicate')"
                                                @click.stop="duplicateSlot(index)"
                                            >
                                                <icon-ic-copy />
                                            </button>
                                            <button
                                                type="button"
                                                class="btn btn-sm btn-link text-danger p-1"
                                                :title="$gettext('Delete')"
                                                @click.stop="entries.splice(index, 1)"
                                            >
                                                <icon-ic-delete />
                                            </button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="form-text">
                            {{ $gettext('Drag a row by its colour bar to reorder; positions are re-spaced automatically. Click a slice of the wheel to jump to its slot.') }}
                        </div>
                    </div>
                </div>
            </div>
        </loading>

        <div class="card-footer d-flex flex-wrap gap-2">
            <button
                v-if="isEditMode"
                type="button"
                class="btn btn-outline-danger"
                :disabled="isBusy"
                @click="doDelete"
            >
                {{ $gettext('Delete') }}
            </button>
            <button
                v-if="isEditMode"
                type="button"
                class="btn btn-outline-secondary"
                :disabled="isBusy"
                @click="doDuplicate"
            >
                {{ $gettext('Duplicate') }}
            </button>
            <div class="ms-auto d-flex gap-2">
                <button
                    type="button"
                    class="btn btn-outline-secondary"
                    :disabled="isBusy"
                    @click="emit('cancel')"
                >
                    {{ $gettext('Cancel') }}
                </button>
                <button
                    type="button"
                    class="btn btn-primary"
                    :disabled="isBusy"
                    @click="doSubmit"
                >
                    {{ isBusy && loaded ? $gettext('Saving…') : $gettext('Save Clock Wheel') }}
                </button>
            </div>
        </div>
    </section>
</template>

<script setup lang="ts">
import {computed, nextTick, onMounted, reactive, ref, useTemplateRef, watch} from 'vue';
import {useDraggable} from 'vue-draggable-plus';
import {useAxios} from '~/vendor/axios';
import {useTranslate} from '~/vendor/gettext';
import {useNotify} from '~/components/Common/Toasts/useNotify.ts';
import {useDialog} from '~/components/Common/Dialogs/useDialog.ts';
import Loading from '~/components/Common/Loading.vue';
import WheelDial from '~/components/Stations/ClockWheels/WheelDial.vue';
import IconIcDelete from '~icons/ic/baseline-delete';
import IconIcCopy from '~icons/ic/baseline-content-copy';
import {useClockWheelSlotOptions} from '~/functions/useClockWheelSlotOptions.ts';
import {clockWheelTypeColor} from '~/functions/clockWheelTypeColors.ts';
import {formatMediaType, getMediaTypeOptions, type MediaTypeValue} from '~/functions/mediaTypes.ts';
import {
    applyDragOrderToPositions,
    estimateClockWheelLoopSeconds,
    formatClockWheelPosition,
    getClockWheelContentDensity,
    getClockWheelTimelineWarnings,
    isClockWheelLayoutValid,
    parseClockWheelPosition,
    sortClockWheelEntries,
} from '~/functions/clockWheelPosition.ts';
import {
    defaultClockWheelSlotEditorRow,
    mapApiSlotToEditorRow,
    mapEditorRowToApiSlot,
    type ClockWheelSlotEditorRow,
} from '~/functions/clockWheelSlotEditor.ts';

const props = defineProps<{
    createUrl: string;
    recordUrl?: string | null;
}>();

const emit = defineEmits<{
    (e: 'saved'): void;
    (e: 'cancel'): void;
}>();

const {$gettext, $ngettext} = useTranslate();
const {axios} = useAxios();
const {notifySuccess} = useNotify();
const {confirmDelete} = useDialog();
const {categoryOptions, load: loadCategories} = useClockWheelSlotOptions();

const isEditMode = computed(() => Boolean(props.recordUrl));
const isBusy = ref(false);
const loaded = ref(false);
const submitted = ref(false);
const error = ref<string | null>(null);
const selectedIndex = ref<number | null>(null);

const form = ref({
    name: '',
    color: '#2196f3',
    is_active: true,
    fill_strategy: 'conservative',
});
const daypartId = ref<number | null>(null);
const inheritedTemplateSlots = ref(false);
const entries = reactive<ClockWheelSlotEditorRow[]>([]);

// Stable row keys so inputs keep focus while positions change.
let keySeq = 0;
const entryKeys = reactive<number[]>([]);
watch(() => entries.length, (len) => {
    while (entryKeys.length < len) {
        entryKeys.push(++keySeq);
    }
    entryKeys.splice(len);
}, {immediate: true});

const isDaypartManaged = computed(() => daypartId.value != null && daypartId.value > 0);

const typeOptions = computed(() =>
    getMediaTypeOptions($gettext).map((opt) => ({
        value: opt.value,
        short: formatMediaType(opt.value, $gettext),
    }))
);

const algorithmOptions = computed(() => [
    {value: 'random', text: $gettext('Random')},
    {value: 'sequential', text: $gettext('Sequential (oldest first)')},
    {value: 'oldest_album', text: $gettext('Oldest Album')},
    {value: 'oldest_artist', text: $gettext('Oldest Artist')},
    {value: 'oldest_track', text: $gettext('Oldest Track')},
    {value: 'most_recent_album', text: $gettext('Most Recent Album')},
    {value: 'most_recent_artist', text: $gettext('Most Recent Artist')},
]);

const dialSlots = computed(() =>
    entries.map((e) => ({position_seconds: e.position_seconds, type: e.type, label: formatMediaType(e.type, $gettext)}))
);

const density = computed(() => getClockWheelContentDensity(entries));
const distributionRows = computed(() => [
    {key: 'music', label: $gettext('Music'), percent: density.value.musicPercent, color: clockWheelTypeColor('music')},
    {key: 'talk', label: $gettext('Talk'), percent: density.value.talkPercent, color: clockWheelTypeColor('talk')},
    {key: 'id', label: $gettext('Station ID'), percent: density.value.idPercent, color: clockWheelTypeColor('id')},
    {key: 'promo', label: $gettext('Promo / Ad'), percent: density.value.promoAdPercent, color: clockWheelTypeColor('promo')},
]);

const estimatedLoopSeconds = computed(() => estimateClockWheelLoopSeconds(entries));
const layoutValid = computed(() => isClockWheelLayoutValid(entries));
const timelineWarnings = computed(() => getClockWheelTimelineWarnings(entries, $gettext));
const rowHasWarning = (index: number) => timelineWarnings.value.some((w) => w.index === index);

const formatPosition = formatClockWheelPosition;

const TYPICAL_SECONDS: Record<string, number> = {music: 210, talk: 300, id: 30, promo: 60, ad: 60};

const addSlot = (type: MediaTypeValue) => {
    sortClockWheelEntries(entries);
    const last = entries[entries.length - 1];
    const position = last
        ? Math.min(3599, last.position_seconds + (last.duration_seconds || TYPICAL_SECONDS[last.type] || 210))
        : 0;
    entries.push({...defaultClockWheelSlotEditorRow(position), type});
    sortClockWheelEntries(entries);
    selectedIndex.value = entries.findIndex((e) => e.position_seconds === position && e.type === type);
};

const duplicateSlot = (index: number) => {
    const source = entries[index];
    if (!source) {
        return;
    }
    const next = entries[index + 1];
    const step = source.duration_seconds || TYPICAL_SECONDS[source.type] || 210;
    let position = Math.min(3599, source.position_seconds + step);
    if (next && position >= next.position_seconds) {
        position = Math.floor((source.position_seconds + next.position_seconds) / 2);
    }
    entries.push({...source, position_seconds: position});
    sortClockWheelEntries(entries);
};

const onPositionChange = (entry: ClockWheelSlotEditorRow, event: Event) => {
    const target = event.target as HTMLInputElement;
    entry.position_seconds = parseClockWheelPosition(target.value);
    target.value = formatPosition(entry.position_seconds);
    sortClockWheelEntries(entries);
};

const $tbody = useTemplateRef('$tbody');

const selectRow = (index: number) => {
    selectedIndex.value = index;
    $tbody.value?.querySelector(`tr[data-entry-index="${index}"]`)
        ?.scrollIntoView({behavior: 'smooth', block: 'nearest'});
};

const requestError = (err: unknown, fallback: string): string =>
    (err as {response?: {data?: {message?: string}}})?.response?.data?.message ?? fallback;

onMounted(async () => {
    isBusy.value = true;
    try {
        await loadCategories();
        if (props.recordUrl) {
            const {data} = await axios.get<Record<string, unknown>>(props.recordUrl);
            form.value = {
                name: typeof data.name === 'string' ? data.name : '',
                color: typeof data.color === 'string' ? data.color : '#2196f3',
                is_active: Boolean(data.is_active),
                fill_strategy: data.fill_strategy === 'aggressive' ? 'aggressive' : 'conservative',
            };
            daypartId.value = data.daypart_id != null ? Number(data.daypart_id) : null;
            inheritedTemplateSlots.value = Boolean(data.inherits_template_slots);
            const slots = Array.isArray(data.slots) ? data.slots as Record<string, unknown>[] : [];
            entries.splice(0, entries.length, ...slots.map((s) => mapApiSlotToEditorRow(s)));
            sortClockWheelEntries(entries);
        }
        loaded.value = true;
    } catch (err) {
        error.value = requestError(err, $gettext('Could not load this clock wheel.'));
    } finally {
        isBusy.value = false;
    }

    await nextTick();
    if ($tbody.value) {
        useDraggable($tbody.value, ref(entries), {
            handle: '.drag-handle',
            animation: 150,
            onEnd() {
                applyDragOrderToPositions(entries);
                sortClockWheelEntries(entries);
            },
        });
    }
});

// Only the fields this page edits are sent; schedules, template links and
// separation settings stored on the wheel are left untouched by the API.
const buildPayload = (): Record<string, unknown> | null => {
    submitted.value = true;
    if (!form.value.name.trim()) {
        error.value = $gettext('Please enter a name for this clock wheel.');
        return null;
    }
    const payload: Record<string, unknown> = {
        ...form.value,
        name: form.value.name.trim(),
        slots: entries.map((e) => mapEditorRowToApiSlot(e)),
    };
    // Slots edited here become this wheel's own layout.
    if (inheritedTemplateSlots.value && !isDaypartManaged.value) {
        payload.inherits_template_slots = false;
    }
    return payload;
};

const run = async (action: () => Promise<void>, fallback: string) => {
    isBusy.value = true;
    error.value = null;
    try {
        await action();
    } catch (err) {
        error.value = requestError(err, fallback);
    } finally {
        isBusy.value = false;
    }
};

const doSubmit = async () => {
    const payload = buildPayload();
    if (!payload) {
        return;
    }
    await run(async () => {
        if (props.recordUrl) {
            await axios.put(props.recordUrl, payload);
        } else {
            await axios.post(props.createUrl, payload);
        }
        notifySuccess($gettext('Clock Wheel saved.'));
        emit('saved');
    }, $gettext('Could not save this clock wheel.'));
};

const doDuplicate = async () => {
    const payload = buildPayload();
    if (!payload) {
        return;
    }
    await run(async () => {
        await axios.post(props.createUrl, {
            ...payload,
            name: $gettext('%{name} Copy', {name: form.value.name}),
            is_active: false,
            inherits_template_slots: false,
        });
        notifySuccess($gettext('Clock Wheel duplicated as an inactive copy.'));
        emit('saved');
    }, $gettext('Could not duplicate this clock wheel.'));
};

const doDelete = async () => {
    if (!props.recordUrl) {
        return;
    }
    const {value} = await confirmDelete({title: $gettext('Delete “%{name}”?', {name: form.value.name})});
    if (!value) {
        return;
    }
    await run(async () => {
        await axios.delete(props.recordUrl as string);
        notifySuccess($gettext('Clock Wheel deleted.'));
        emit('saved');
    }, $gettext('Could not delete this clock wheel.'));
};
</script>

<style scoped>
.legend-dot {
    display: inline-block;
    width: .7rem;
    height: .7rem;
    border-radius: 50%;
}

.type-bar {
    display: inline-block;
    width: .4rem;
    height: 1.6rem;
    border-radius: .2rem;
    vertical-align: middle;
}

.drag-handle {
    cursor: grab;
}

.slot-table tbody tr {
    cursor: pointer;
}
</style>
