<template>
    <section
        class="card"
        role="region"
        aria-labelledby="hdr_clock_wheel_editor"
    >
        <div class="card-header text-bg-primary d-flex align-items-center gap-3 flex-wrap">
            <button
                type="button"
                class="btn btn-sm btn-light"
                @click="emit('cancel')"
            >
                ← {{ isTemplate ? $gettext('All Hour Templates') : $gettext('All Clock Wheels') }}
            </button>
            <h2
                id="hdr_clock_wheel_editor"
                class="card-title my-0 flex-fill"
            >
                {{ isEditMode ? form.name || titleEdit : titleNew }}
            </h2>
        </div>

        <div
            v-if="error"
            class="alert alert-danger rounded-0 mb-0"
        >
            {{ error }}
        </div>
        <div
            v-if="isTemplate"
            class="alert alert-info rounded-0 mb-0"
        >
            {{ $gettext('An hour template is a master clock wheel. Every wheel made from it, including the hourly wheels a daypart creates, follows these slots; save here and they all update.') }}
        </div>
        <div
            v-if="isDaypartManaged"
            class="alert alert-warning rounded-0 mb-0"
        >
            {{ $gettext('This wheel was generated by a daypart; a daypart re-sync can replace its slots.') }}
        </div>

        <ul
            v-if="hasViewTabs"
            class="nav nav-tabs px-3 pt-2"
            role="tablist"
        >
            <li
                v-for="tab in viewTabs"
                :key="tab.key"
                class="nav-item"
                role="presentation"
            >
                <button
                    type="button"
                    class="nav-link"
                    :class="{active: view === tab.key}"
                    role="tab"
                    :aria-selected="view === tab.key"
                    @click="view = tab.key"
                >
                    {{ tab.label }}
                </button>
            </li>
        </ul>

        <div
            v-if="hasViewTabs && view === 'preview'"
            class="card-body"
        >
            <wheel-log-panel
                :url="recordUrl + '/log'"
                mode="upcoming"
            />
        </div>

        <div
            v-if="hasViewTabs && view === 'aired'"
            class="card-body"
        >
            <wheel-log-panel
                :url="recordUrl + '/log'"
                mode="aired"
            />
            <h3 class="h6 mt-4">
                {{ $gettext('Summary') }}
            </h3>
            <analytics-panel :url="recordUrl + '/analytics'" />
        </div>

        <loading
            :loading="isBusy && !loaded"
            lazy
        >
            <div
                v-show="view === 'edit'"
                class="card-body"
            >
                <div class="row g-4">
                    <div class="col-lg-4">
                        <div class="d-flex justify-content-center mb-3">
                            <wheel-dial
                                :slots="dialSlots"
                                :size="300"
                                :center-label="form.name || (isTemplate ? $gettext('New Template') : $gettext('New Wheel'))"
                                :center-sub="$ngettext('%{n} slot', '%{n} slots', entries.length, {n: String(entries.length)})"
                                :selected-index="selectedIndex"
                                :aria-label="$gettext('Clock wheel preview')"
                                @select="selectRow"
                            />
                        </div>

                        <div class="d-flex flex-wrap justify-content-center gap-3 small mb-3">
                            <span
                                v-for="opt in typeOptions"
                                :key="opt.value"
                                class="d-inline-flex align-items-center gap-1"
                            >
                                <span
                                    class="legend-dot"
                                    :style="{background: clockWheelTypeColor(opt.value)}"
                                />
                                {{ opt.short }}
                            </span>
                        </div>

                        <div class="card bg-body-tertiary">
                            <div class="card-body">
                                <h3 class="h6 mb-3">
                                    {{ $gettext('Hour Distribution') }}
                                </h3>
                                <div
                                    v-for="row in distributionRows"
                                    :key="row.key"
                                    class="mb-2"
                                >
                                    <div class="d-flex justify-content-between small mb-1">
                                        <span>{{ row.label }}</span>
                                        <span class="fw-semibold">{{ row.percent }}%</span>
                                    </div>
                                    <div
                                        class="progress"
                                        style="height: 6px;"
                                    >
                                        <div
                                            class="progress-bar"
                                            :style="{width: row.percent + '%', background: row.color}"
                                        />
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <div class="d-flex justify-content-between small mb-1">
                                        <span>{{ $gettext('Hour budget') }}</span>
                                        <span
                                            class="fw-semibold"
                                            :class="{'text-danger': hourBudget.overSeconds > 0}"
                                        >
                                            {{ formatLength(hourBudget.usedSeconds) }} / {{ formatLength(hourBudget.availableSeconds) }}
                                        </span>
                                    </div>
                                    <div
                                        class="progress"
                                        style="height: 6px;"
                                    >
                                        <div
                                            class="progress-bar"
                                            :class="hourBudget.overSeconds > 0 ? 'bg-danger' : (hourBudget.freeSeconds > 90 ? 'bg-warning' : 'bg-success')"
                                            :style="{width: budgetPercent + '%'}"
                                        />
                                    </div>
                                    <div class="small mt-1">
                                        <span
                                            v-if="hourBudget.overSeconds > 0"
                                            class="text-danger"
                                        >
                                            {{ $gettext('Over by') }} {{ formatLength(hourBudget.overSeconds) }}:
                                            {{ slotLengths?.top_of_hour_id_enabled
                                                ? $gettext('the last entries run into the :59:59 ID.')
                                                : $gettext('the last entries will not fit in the hour.') }}
                                        </span>
                                        <span
                                            v-else-if="hourBudget.freeSeconds > 90"
                                            class="text-muted"
                                        >
                                            {{ formatLength(hourBudget.freeSeconds) }} {{ $gettext('free') }}
                                            <template v-if="hourBudget.roomForSongs > 0">
                                                ({{ $gettext('room for about') }} {{ hourBudget.roomForSongs }}
                                                {{ hourBudget.roomForSongs === 1 ? $gettext('more song') : $gettext('more songs') }})
                                            </template>
                                        </span>
                                        <span
                                            v-else
                                            class="text-success"
                                        >
                                            {{ $gettext('Fills the hour') }}
                                        </span>
                                    </div>
                                    <button
                                        v-if="entries.length > 0 && !layoutValid"
                                        type="button"
                                        class="btn btn-sm btn-success w-100 mt-2"
                                        @click="runFix"
                                    >
                                        {{ $gettext('Fix my hour') }}
                                    </button>
                                    <div
                                        v-if="!slotLengths"
                                        class="small text-muted"
                                    >
                                        {{ $gettext('Using typical lengths; library lengths could not be loaded.') }}
                                    </div>
                                </div>
                                <p class="small text-muted mb-0 mt-2">
                                    <span
                                        class="badge ms-1"
                                        :class="layoutValid ? 'text-bg-success' : 'text-bg-warning'"
                                    >
                                        {{ layoutValid ? $gettext('Valid layout') : $gettext('Needs review') }}
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-8">
                        <h3 class="h6">
                            {{ isTemplate ? $gettext('Template Details') : $gettext('Wheel Details') }}
                        </h3>
                        <div class="row g-3 mb-4">
                            <div :class="isTemplate ? 'col-md-10' : 'col-md-5'">
                                <label
                                    class="form-label"
                                    for="cw_name"
                                >{{ $gettext('Name') }}</label>
                                <input
                                    id="cw_name"
                                    v-model="form.name"
                                    type="text"
                                    class="form-control"
                                    :class="{'is-invalid': submitted && !form.name.trim()}"
                                    required
                                >
                            </div>
                            <div class="col-md-2 col-4">
                                <label
                                    class="form-label"
                                    for="cw_color"
                                >{{ $gettext('Color') }}</label>
                                <input
                                    id="cw_color"
                                    v-model="form.color"
                                    type="color"
                                    class="form-control form-control-color w-100"
                                >
                            </div>
                            <div
                                v-if="!isTemplate"
                                class="col-md-2 col-8"
                            >
                                <label
                                    class="form-label"
                                    for="cw_status"
                                >{{ $gettext('Status') }}</label>
                                <select
                                    id="cw_status"
                                    v-model="form.is_active"
                                    class="form-select"
                                >
                                    <option :value="true">
                                        {{ $gettext('Active') }}
                                    </option>
                                    <option :value="false">
                                        {{ $gettext('Inactive') }}
                                    </option>
                                </select>
                            </div>
                            <div
                                v-if="!isTemplate"
                                class="col-md-3"
                            >
                                <label
                                    class="form-label"
                                    for="cw_fill"
                                >{{ $gettext('Fill Strategy') }}</label>
                                <select
                                    id="cw_fill"
                                    v-model="form.fill_strategy"
                                    class="form-select"
                                >
                                    <option value="conservative">
                                        {{ $gettext('Conservative') }}
                                    </option>
                                    <option value="aggressive">
                                        {{ $gettext('Aggressive') }}
                                    </option>
                                </select>
                            </div>
                            <div
                                v-if="isTemplate"
                                class="col-12 form-text mt-1"
                            >
                                {{ $gettext('Templates never air by themselves. Put one on air with a Daypart.') }}
                            </div>
                            <div
                                v-else
                                class="col-12 form-text mt-1"
                            >
                                {{ $gettext('Conservative skips a slot that does not fit its window; Aggressive picks the shortest track that fits.') }}
                                {{ $gettext('Air times are set on the Schedule page.') }}
                            </div>
                        </div>

                        <div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-2">
                            <h3 class="h6 mb-0">
                                {{ $gettext('Slots') }} ({{ entries.length }})
                            </h3>
                            <div class="d-flex flex-wrap gap-1">
                                <button
                                    type="button"
                                    class="btn btn-sm btn-primary"
                                    @click="openBuilder"
                                >
                                    {{ $gettext('Build one for me') }}
                                </button>
                                <button
                                    v-for="opt in typeOptions"
                                    :key="opt.value"
                                    type="button"
                                    class="btn btn-sm btn-outline-secondary"
                                    @click="addSlot(opt.value)"
                                >
                                    <span
                                        class="legend-dot me-1"
                                        :style="{background: clockWheelTypeColor(opt.value)}"
                                    />
                                    + {{ opt.short }}
                                </button>
                            </div>
                        </div>

                        <div
                            v-if="builderOpen"
                            class="card border-primary mb-3"
                        >
                            <div class="card-body">
                                <h4 class="h6">
                                    {{ $gettext('Build one for me') }}
                                </h4>
                                <p class="small text-muted">
                                    {{ $gettext('Answer a few questions and a full hour is laid out for you, sized to your real song lengths. You can still change anything afterwards.') }}
                                </p>
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <label
                                            class="form-label small"
                                            for="cw_build_music"
                                        >{{ $gettext('What music should play?') }}</label>
                                        <select
                                            id="cw_build_music"
                                            v-model="builder.musicKey"
                                            class="form-select form-select-sm"
                                        >
                                            <optgroup
                                                v-for="grp in musicContentGroups"
                                                :key="grp.label"
                                                :label="grp.label"
                                            >
                                                <option
                                                    v-for="opt in grp.options"
                                                    :key="opt.key"
                                                    :value="opt.key"
                                                >
                                                    {{ opt.label }}
                                                </option>
                                            </optgroup>
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label
                                            class="form-label small"
                                            for="cw_build_playlist"
                                        >{{ $gettext('From a playlist or smart block? (optional)') }}</label>
                                        <select
                                            id="cw_build_playlist"
                                            v-model="builder.playlistKey"
                                            class="form-select form-select-sm"
                                        >
                                            <option value="">
                                                {{ $gettext('— Whole library') }}
                                            </option>
                                            <optgroup
                                                v-for="grp in playlistGroups"
                                                :key="grp.label"
                                                :label="grp.label"
                                            >
                                                <option
                                                    v-for="opt in grp.options"
                                                    :key="opt.key"
                                                    :value="opt.key"
                                                >
                                                    {{ opt.label }}
                                                </option>
                                            </optgroup>
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label
                                            class="form-label small"
                                            for="cw_build_breaks"
                                        >{{ $gettext('How many promo breaks per hour?') }}</label>
                                        <select
                                            id="cw_build_breaks"
                                            v-model.number="builder.promoBreaks"
                                            class="form-select form-select-sm"
                                        >
                                            <option
                                                v-for="n in [0, 1, 2, 3, 4]"
                                                :key="n"
                                                :value="n"
                                            >
                                                {{ n === 0 ? $gettext('None') : n }}
                                            </option>
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label
                                            class="form-label small"
                                            for="cw_build_per"
                                        >{{ $gettext('Promos in each break?') }}</label>
                                        <select
                                            id="cw_build_per"
                                            v-model.number="builder.promosPerBreak"
                                            class="form-select form-select-sm"
                                            :disabled="builder.promoBreaks === 0"
                                        >
                                            <option :value="1">
                                                1
                                            </option>
                                            <option :value="2">
                                                2
                                            </option>
                                        </select>
                                    </div>
                                    <div
                                        v-if="!slotLengths?.top_of_hour_id_enabled"
                                        class="col-12"
                                    >
                                        <div class="form-check">
                                            <input
                                                id="cw_build_id"
                                                v-model="builder.idAtTop"
                                                class="form-check-input"
                                                type="checkbox"
                                            >
                                            <label
                                                class="form-check-label small"
                                                for="cw_build_id"
                                            >{{ $gettext('Start the hour with a station ID') }}</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex gap-2 mt-3">
                                    <button
                                        type="button"
                                        class="btn btn-sm btn-primary"
                                        @click="runBuild"
                                    >
                                        {{ $gettext('Build it') }}
                                    </button>
                                    <button
                                        type="button"
                                        class="btn btn-sm btn-outline-secondary"
                                        @click="builderOpen = false"
                                    >
                                        {{ $gettext('Cancel') }}
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div
                            v-if="proposal"
                            class="card border-success mb-3"
                        >
                            <div class="card-body">
                                <h4 class="h6">
                                    {{ proposal.title }}
                                </h4>
                                <ul class="small mb-2">
                                    <li
                                        v-for="(c, ci) in proposal.result.changes"
                                        :key="ci"
                                    >
                                        {{ c }}
                                    </li>
                                </ul>
                                <p class="small mb-2">
                                    {{ $gettext('Before') }}: {{ entries.length }} {{ $gettext('slots') }}, {{ formatLength(hourBudget.usedSeconds) }}
                                    → {{ $gettext('After') }}: <strong>{{ proposal.result.entries.length }} {{ $gettext('slots') }}, {{ formatLength(proposalBudget.usedSeconds) }}</strong>
                                    {{ $gettext('of') }} {{ formatLength(proposalBudget.availableSeconds) }}
                                    <span
                                        v-if="proposalWarnings === 0"
                                        class="badge text-bg-success ms-1"
                                    >{{ $gettext('No problems') }}</span>
                                    <span
                                        v-else
                                        class="badge text-bg-warning ms-1"
                                    >{{ proposalWarnings }} {{ $gettext('to review') }}</span>
                                </p>
                                <ol class="small text-muted mb-3 proposal-list">
                                    <li
                                        v-for="(row, ri) in proposal.result.entries"
                                        :key="ri"
                                    >
                                        {{ formatPosition(row.position_seconds) }} — {{ clockWheelContentLabel(row, contentGroups, slotLengths) }}
                                    </li>
                                </ol>
                                <div class="d-flex gap-2">
                                    <button
                                        type="button"
                                        class="btn btn-sm btn-success"
                                        @click="applyProposal"
                                    >
                                        {{ $gettext('Apply') }}
                                    </button>
                                    <button
                                        type="button"
                                        class="btn btn-sm btn-outline-secondary"
                                        @click="proposal = null"
                                    >
                                        {{ $gettext('Cancel') }}
                                    </button>
                                </div>
                                <div class="form-text">
                                    {{ $gettext('Nothing is saved until you click Save Clock Wheel.') }}
                                </div>
                            </div>
                        </div>

                        <div
                            v-if="timelineWarnings.length > 0 && !proposal"
                            class="alert alert-warning py-2 small"
                        >
                            <div class="d-flex align-items-center gap-2 mb-1">
                                <strong class="me-auto">
                                    {{ timelineWarnings.length === 1
                                        ? $gettext('1 thing to fix in this hour')
                                        : $gettext('%{n} things to fix in this hour').replace('%{n}', String(timelineWarnings.length)) }}
                                </strong>
                                <button
                                    type="button"
                                    class="btn btn-sm btn-success"
                                    @click="runFix"
                                >
                                    {{ $gettext('Fix my hour') }}
                                </button>
                            </div>
                            <div
                                v-for="(warn, wi) in timelineWarnings"
                                :key="wi"
                            >
                                <strong>{{ formatPosition(entries[warn.index]?.position_seconds ?? 0) }}</strong>
                                ({{ clockWheelContentLabel(entries[warn.index], contentGroups, slotLengths) }}): {{ warn.message }}
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-sm table-striped align-middle mb-0 slot-table">
                                <thead>
                                    <tr>
                                        <th style="width: 1.5rem;" />
                                        <th>{{ $gettext('Position') }}</th>
                                        <th>{{ $gettext('What plays here') }}</th>
                                        <th>{{ $gettext('Playlist / Smart block') }}</th>
                                        <th>{{ $gettext('Algorithm') }}</th>
                                        <th>{{ $gettext('Max Sec') }}</th>
                                        <th class="text-end">
                                            <span class="visually-hidden">{{ $gettext('Actions') }}</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody ref="$tbody">
                                    <tr v-if="entries.length === 0">
                                        <td
                                            colspan="7"
                                            class="text-center text-muted py-4"
                                        >
                                            {{ $gettext('No slots yet. Use the buttons above to build your hour.') }}
                                        </td>
                                    </tr>
                                    <tr
                                        v-for="(entry, index) in entries"
                                        :key="entryKeys[index]"
                                        :data-entry-index="index"
                                        :class="{'table-active': selectedIndex === index, 'table-warning': rowHasWarning(index)}"
                                        @click="selectedIndex = index"
                                    >
                                        <td class="drag-handle text-muted text-center">
                                            <span
                                                class="type-bar"
                                                :style="{background: clockWheelTypeColor(entry.type)}"
                                            />
                                        </td>
                                        <td style="min-width: 5.5rem;">
                                            <input
                                                :value="formatPosition(entry.position_seconds)"
                                                type="text"
                                                class="form-control form-control-sm"
                                                :aria-label="$gettext('Position (m:s)')"
                                                placeholder="0:00"
                                                @change="onPositionChange(entry, $event)"
                                            >
                                        </td>
                                        <td style="min-width: 12rem;">
                                            <select
                                                :value="clockWheelContentKey(entry)"
                                                class="form-select form-select-sm"
                                                :aria-label="$gettext('What plays here')"
                                                @change="onContentChange(entry, $event)"
                                            >
                                                <optgroup
                                                    v-for="grp in contentGroups"
                                                    :key="grp.label"
                                                    :label="grp.label"
                                                >
                                                    <option
                                                        v-for="opt in grp.options"
                                                        :key="opt.key"
                                                        :value="opt.key"
                                                    >
                                                        {{ opt.label }}
                                                    </option>
                                                </optgroup>
                                            </select>
                                        </td>
                                        <td style="min-width: 10rem;">
                                            <select
                                                :value="clockWheelPlaylistKey(entry)"
                                                class="form-select form-select-sm"
                                                :aria-label="$gettext('Playlist / Smart block')"
                                                @change="onPlaylistChange(entry, $event)"
                                            >
                                                <option value="">
                                                    {{ $gettext('— Whole library') }}
                                                </option>
                                                <optgroup
                                                    v-for="grp in playlistGroups"
                                                    :key="grp.label"
                                                    :label="grp.label"
                                                >
                                                    <option
                                                        v-for="opt in grp.options"
                                                        :key="opt.key"
                                                        :value="opt.key"
                                                    >
                                                        {{ opt.label }}
                                                    </option>
                                                </optgroup>
                                            </select>
                                        </td>
                                        <td style="min-width: 9rem;">
                                            <select
                                                v-model="entry.algorithm"
                                                class="form-select form-select-sm"
                                                :aria-label="$gettext('Algorithm')"
                                            >
                                                <option
                                                    v-for="opt in algorithmOptions"
                                                    :key="opt.value"
                                                    :value="opt.value"
                                                >
                                                    {{ opt.text }}
                                                </option>
                                            </select>
                                        </td>
                                        <td style="min-width: 5.5rem;">
                                            <input
                                                v-model.number="entry.duration_seconds"
                                                type="number"
                                                min="0"
                                                max="3600"
                                                class="form-control form-control-sm"
                                                :aria-label="$gettext('Max seconds')"
                                                :placeholder="$gettext('Auto')"
                                            >
                                        </td>
                                        <td class="text-end text-nowrap">
                                            <button
                                                type="button"
                                                class="btn btn-sm btn-link text-secondary p-1"
                                                :title="$gettext('Duplicate')"
                                                @click.stop="duplicateSlot(index)"
                                            >
                                                <icon-ic-copy />
                                            </button>
                                            <button
                                                type="button"
                                                class="btn btn-sm btn-link text-danger p-1"
                                                :title="$gettext('Delete')"
                                                @click.stop="entries.splice(index, 1)"
                                            >
                                                <icon-ic-delete />
                                            </button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="form-text">
                            {{ $gettext('Drag a row by its colour bar to reorder; positions are re-spaced automatically. Click a slice of the wheel to jump to its slot.') }}
                        </div>
                    </div>
                </div>
            </div>
        </loading>

        <div class="card-footer d-flex flex-wrap gap-2">
            <button
                v-if="isEditMode"
                type="button"
                class="btn btn-outline-danger"
                :disabled="isBusy"
                @click="doDelete"
            >
                {{ $gettext('Delete') }}
            </button>
            <button
                v-if="isEditMode && !isTemplate"
                type="button"
                class="btn btn-outline-secondary"
                :disabled="isBusy"
                @click="doDuplicate"
            >
                {{ $gettext('Duplicate') }}
            </button>
            <div class="ms-auto d-flex gap-2">
                <button
                    type="button"
                    class="btn btn-outline-secondary"
                    :disabled="isBusy"
                    @click="emit('cancel')"
                >
                    {{ $gettext('Cancel') }}
                </button>
                <button
                    type="button"
                    class="btn btn-primary"
                    :disabled="isBusy"
                    @click="doSubmit"
                >
                    {{ isBusy && loaded ? $gettext('Saving…') : (isTemplate ? $gettext('Save Template') : $gettext('Save Clock Wheel')) }}
                </button>
            </div>
        </div>
    </section>
</template>

<script setup lang="ts">
import {computed, nextTick, onMounted, reactive, ref, useTemplateRef, watch} from 'vue';
import {useDraggable} from 'vue-draggable-plus';
import {useAxios} from '~/vendor/axios';
import {useTranslate} from '~/vendor/gettext';
import {useNotify} from '~/components/Common/Toasts/useNotify.ts';
import {useDialog} from '~/components/Common/Dialogs/useDialog.ts';
import Loading from '~/components/Common/Loading.vue';
import WheelDial from '~/components/Stations/ClockWheels/WheelDial.vue';
import WheelLogPanel from '~/components/Stations/ClockWheels/WheelLogPanel.vue';
import AnalyticsPanel from '~/components/Stations/ClockWheels/AnalyticsPanel.vue';
import IconIcDelete from '~icons/ic/baseline-delete';
import IconIcCopy from '~icons/ic/baseline-content-copy';
import {useClockWheelSlotOptions} from '~/functions/useClockWheelSlotOptions.ts';
import {clockWheelTypeColor} from '~/functions/clockWheelTypeColors.ts';
import {formatMediaType, getMediaTypeOptions, type MediaTypeValue} from '~/functions/mediaTypes.ts';
import {
    applyDragOrderToPositions,
    formatClockWheelPosition,
    getClockWheelContentDensity,
    getClockWheelTimelineWarnings,
    parseClockWheelPosition,
    sortClockWheelEntries,
} from '~/functions/clockWheelPosition.ts';
import {
    buildClockWheelHour,
    estimateEntrySeconds,
    fixClockWheelHour,
    getClockWheelFitWarnings,
    getClockWheelHourBudget,
    type ClockWheelFixResult,
    type ClockWheelSlotLengths,
} from '~/functions/clockWheelHourFit.ts';
import {
    applyClockWheelContentKey,
    applyClockWheelPlaylistKey,
    buildClockWheelContentGroups,
    buildClockWheelPlaylistGroups,
    clockWheelContentKey,
    clockWheelContentLabel,
    clockWheelPlaylistKey,
} from '~/functions/clockWheelContent.ts';
import {useApiRouter} from '~/functions/useApiRouter.ts';
import {
    defaultClockWheelSlotEditorRow,
    mapApiSlotToEditorRow,
    mapEditorRowToApiSlot,
    type ClockWheelSlotEditorRow,
} from '~/functions/clockWheelSlotEditor.ts';

const props = withDefaults(defineProps<{
    createUrl: string;
    recordUrl?: string | null;
    mode?: 'wheel' | 'template';
    initialView?: 'edit' | 'preview' | 'aired';
}>(), {
    recordUrl: null,
    mode: 'wheel',
    initialView: 'edit',
});

const emit = defineEmits<{
    (e: 'saved'): void;
    (e: 'cancel'): void;
}>();

const {$gettext, $ngettext} = useTranslate();
const {axios} = useAxios();
const {notifySuccess} = useNotify();
const {confirmDelete} = useDialog();
const {categoryOptions, load: loadCategories} = useClockWheelSlotOptions();
const {getStationApiUrl} = useApiRouter();

// Real library lengths and the Top-of-Hour ID timing; until they load (or if
// the request fails) the editor falls back to typical lengths.
const slotLengths = ref<ClockWheelSlotLengths | null>(null);
const loadSlotLengths = async () => {
    try {
        const {data} = await axios.get<ClockWheelSlotLengths>(getStationApiUrl('/clock-wheels/slot-lengths').value);
        slotLengths.value = data;
    } catch {
        slotLengths.value = null;
    }
};

const isEditMode = computed(() => Boolean(props.recordUrl));
const isTemplate = computed(() => props.mode === 'template');
const titleEdit = computed(() => isTemplate.value ? $gettext('Edit Hour Template') : $gettext('Edit Clock Wheel'));
const titleNew = computed(() => isTemplate.value ? $gettext('New Hour Template') : $gettext('New Clock Wheel'));
const noun = computed(() => isTemplate.value ? $gettext('hour template') : $gettext('clock wheel'));
const isBusy = ref(false);
const loaded = ref(false);

// A saved wheel can be previewed and its as-run analytics shown inline, like a
// broadcast scheduler's clock / generated log / as-run views. New wheels and
// hour templates have nothing saved or aired yet, so they only edit.
type EditorView = 'edit' | 'preview' | 'aired';
const view = ref<EditorView>(props.initialView ?? 'edit');
const hasViewTabs = computed(() => isEditMode.value && !isTemplate.value);
const viewTabs = computed<Array<{key: EditorView; label: string}>>(() => [
    {key: 'edit', label: $gettext('Edit')},
    {key: 'preview', label: $gettext('Preview hour')},
    {key: 'aired', label: $gettext('How it aired')},
]);
const submitted = ref(false);
const error = ref<string | null>(null);
const selectedIndex = ref<number | null>(null);

const form = ref({
    name: '',
    color: '#2196f3',
    is_active: true,
    fill_strategy: 'conservative',
});
const daypartId = ref<number | null>(null);
const inheritedTemplateSlots = ref(false);
const entries = reactive<ClockWheelSlotEditorRow[]>([]);

// Stable row keys so inputs keep focus while positions change.
let keySeq = 0;
const entryKeys = reactive<number[]>([]);
watch(() => entries.length, (len) => {
    while (entryKeys.length < len) {
        entryKeys.push(++keySeq);
    }
    entryKeys.splice(len);
}, {immediate: true});

const isDaypartManaged = computed(() => daypartId.value != null && daypartId.value > 0);

const typeOptions = computed(() =>
    getMediaTypeOptions($gettext).map((opt) => ({
        value: opt.value,
        label: opt.label,
        short: formatMediaType(opt.value, $gettext),
    }))
);

const algorithmOptions = computed(() => [
    {value: 'random', text: $gettext('Random')},
    {value: 'sequential', text: $gettext('Sequential (oldest first)')},
    {value: 'oldest_album', text: $gettext('Oldest Album')},
    {value: 'oldest_artist', text: $gettext('Oldest Artist')},
    {value: 'oldest_track', text: $gettext('Oldest Track')},
    {value: 'most_recent_album', text: $gettext('Most Recent Album')},
    {value: 'most_recent_artist', text: $gettext('Most Recent Artist')},
]);

const dialSlots = computed(() =>
    entries.map((e) => ({position_seconds: e.position_seconds, type: e.type, label: formatMediaType(e.type, $gettext)}))
);

const density = computed(() => getClockWheelContentDensity(
    entries.map((e) => ({...e, duration_seconds: estimateEntrySeconds(e, slotLengths.value)}))
));
const distributionRows = computed(() => [
    {key: 'music', label: $gettext('Music'), percent: density.value.musicPercent, color: clockWheelTypeColor('music')},
    {key: 'talk', label: $gettext('Talk'), percent: density.value.talkPercent, color: clockWheelTypeColor('talk')},
    {key: 'id', label: $gettext('Station ID'), percent: density.value.idPercent, color: clockWheelTypeColor('id')},
    {key: 'promo', label: $gettext('Promo / Ad'), percent: density.value.promoAdPercent, color: clockWheelTypeColor('promo')},
]);

const hourBudget = computed(() => getClockWheelHourBudget(entries, slotLengths.value));
const budgetPercent = computed(() =>
    Math.min(100, Math.round((hourBudget.value.usedSeconds / Math.max(1, hourBudget.value.availableSeconds)) * 100))
);
const formatLength = (seconds: number): string => {
    const s = Math.max(0, Math.round(seconds));
    return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
};
const timelineWarnings = computed(() => [
    ...getClockWheelTimelineWarnings(entries, $gettext),
    ...getClockWheelFitWarnings(entries, slotLengths.value, $gettext),
].sort((a, b) => (entries[a.index]?.position_seconds ?? 0) - (entries[b.index]?.position_seconds ?? 0)));
const layoutValid = computed(() => entries.length > 0 && timelineWarnings.value.length === 0
    && hourBudget.value.overSeconds === 0);

// "What plays here": one choice that sets type, category or playlist together.
const contentGroups = computed(() => buildClockWheelContentGroups(
    typeOptions.value,
    categoryOptions.value,
    $gettext,
));
const playlistGroups = computed(() => buildClockWheelPlaylistGroups(slotLengths.value, $gettext));
// The builder's music: the music types and categories only.
const musicContentGroups = computed(() => contentGroups.value
    .map((g) => ({...g, options: g.options.filter((o) => o.type === 'music')}))
    .filter((g) => g.options.length > 0));
const onContentChange = (entry: ClockWheelSlotEditorRow, event: Event) => {
    applyClockWheelContentKey(entry, (event.target as HTMLSelectElement).value);
};
const onPlaylistChange = (entry: ClockWheelSlotEditorRow, event: Event) => {
    applyClockWheelPlaylistKey(entry, (event.target as HTMLSelectElement).value, slotLengths.value);
};

// Fix my hour / Build one for me: a proposal the user reviews, then applies.
const proposal = ref<{title: string; result: ClockWheelFixResult} | null>(null);
const proposalBudget = computed(() => getClockWheelHourBudget(proposal.value?.result.entries ?? [], slotLengths.value));
const proposalWarnings = computed(() =>
    proposal.value ? getClockWheelFitWarnings(proposal.value.result.entries, slotLengths.value, $gettext).length : 0
);

const runFix = () => {
    builderOpen.value = false;
    proposal.value = {
        title: $gettext('Fix my hour: here is what would change'),
        result: fixClockWheelHour([...entries], slotLengths.value, $gettext),
    };
};

const builderOpen = ref(false);
const builder = ref({musicKey: 'type:music', playlistKey: '', promoBreaks: 2, promosPerBreak: 1, idAtTop: true});
const openBuilder = () => {
    proposal.value = null;
    builderOpen.value = true;
};
const runBuild = () => {
    const music = defaultClockWheelSlotEditorRow(0);
    applyClockWheelContentKey(music, builder.value.musicKey);
    applyClockWheelPlaylistKey(music, builder.value.playlistKey, slotLengths.value);
    builderOpen.value = false;
    proposal.value = {
        title: entries.length > 0
            ? $gettext('Build one for me: this would replace the current slots')
            : $gettext('Build one for me: here is your hour'),
        result: buildClockWheelHour({
            music,
            promoBreaks: builder.value.promoBreaks,
            promosPerBreak: builder.value.promosPerBreak,
            idAtTop: builder.value.idAtTop,
        }, slotLengths.value, $gettext),
    };
};

const applyProposal = () => {
    if (!proposal.value) {
        return;
    }
    entries.splice(0, entries.length, ...proposal.value.result.entries);
    sortClockWheelEntries(entries);
    selectedIndex.value = null;
    proposal.value = null;
    notifySuccess($gettext('Slots updated. Click Save Clock Wheel to keep them.'));
};
const rowHasWarning = (index: number) => timelineWarnings.value.some((w) => w.index === index);

const formatPosition = formatClockWheelPosition;


const addSlot = (type: MediaTypeValue) => {
    sortClockWheelEntries(entries);
    const last = entries[entries.length - 1];
    const position = last
        ? Math.min(3599, last.position_seconds + Math.round(estimateEntrySeconds(last, slotLengths.value)))
        : 0;
    const row = {...defaultClockWheelSlotEditorRow(position), type};
    entries.push(row);
    sortClockWheelEntries(entries);
    selectedIndex.value = entries.indexOf(row);
    // The reactive copy, so later edits to it update the page.
    return entries[selectedIndex.value];
};

const duplicateSlot = (index: number) => {
    const source = entries[index];
    if (!source) {
        return;
    }
    const next = entries[index + 1];
    const step = Math.round(estimateEntrySeconds(source, slotLengths.value));
    let position = Math.min(3599, source.position_seconds + step);
    if (next && position >= next.position_seconds) {
        position = Math.floor((source.position_seconds + next.position_seconds) / 2);
    }
    entries.push({...source, position_seconds: position});
    sortClockWheelEntries(entries);
};

const onPositionChange = (entry: ClockWheelSlotEditorRow, event: Event) => {
    const target = event.target as HTMLInputElement;
    entry.position_seconds = parseClockWheelPosition(target.value);
    target.value = formatPosition(entry.position_seconds);
    sortClockWheelEntries(entries);
};

const $tbody = useTemplateRef('$tbody');

const selectRow = (index: number) => {
    selectedIndex.value = index;
    $tbody.value?.querySelector(`tr[data-entry-index="${index}"]`)
        ?.scrollIntoView({behavior: 'smooth', block: 'nearest'});
};

const requestError = (err: unknown, fallback: string): string =>
    (err as {response?: {data?: {message?: string}}})?.response?.data?.message ?? fallback;

onMounted(async () => {
    isBusy.value = true;
    try {
        await Promise.all([loadCategories(), loadSlotLengths()]);
        if (props.recordUrl) {
            const {data} = await axios.get<Record<string, unknown>>(props.recordUrl);
            form.value = {
                name: typeof data.name === 'string' ? data.name : '',
                color: typeof data.color === 'string' ? data.color : '#2196f3',
                is_active: Boolean(data.is_active),
                fill_strategy: data.fill_strategy === 'aggressive' ? 'aggressive' : 'conservative',
            };
            daypartId.value = data.daypart_id != null ? Number(data.daypart_id) : null;
            inheritedTemplateSlots.value = Boolean(data.inherits_template_slots);
            const slots = Array.isArray(data.slots) ? data.slots as Record<string, unknown>[] : [];
            entries.splice(0, entries.length, ...slots.map((s) => mapApiSlotToEditorRow(s)));
            sortClockWheelEntries(entries);
        }
        loaded.value = true;
    } catch (err) {
        error.value = requestError(err, $gettext('Could not load this %{noun}.', {noun: noun.value}));
    } finally {
        isBusy.value = false;
    }

    await nextTick();
    if ($tbody.value) {
        useDraggable($tbody.value, ref(entries), {
            handle: '.drag-handle',
            animation: 150,
            onEnd() {
                applyDragOrderToPositions(entries);
                sortClockWheelEntries(entries);
            },
        });
    }
});

// Only the fields this page edits are sent; schedules, template links and
// separation settings stored on the wheel are left untouched by the API.
const buildPayload = (): Record<string, unknown> | null => {
    submitted.value = true;
    if (!form.value.name.trim()) {
        error.value = $gettext('Please enter a name for this %{noun}.', {noun: noun.value});
        return null;
    }
    const slots = entries.map((e) => mapEditorRowToApiSlot(e));
    if (isTemplate.value) {
        return {name: form.value.name.trim(), color: form.value.color, slots};
    }
    const payload: Record<string, unknown> = {
        ...form.value,
        name: form.value.name.trim(),
        slots,
    };
    // Slots edited here become this wheel's own layout.
    if (inheritedTemplateSlots.value && !isDaypartManaged.value) {
        payload.inherits_template_slots = false;
    }
    return payload;
};

const run = async (action: () => Promise<void>, fallback: string) => {
    isBusy.value = true;
    error.value = null;
    try {
        await action();
    } catch (err) {
        error.value = requestError(err, fallback);
    } finally {
        isBusy.value = false;
    }
};

const doSubmit = async () => {
    const payload = buildPayload();
    if (!payload) {
        return;
    }
    await run(async () => {
        if (props.recordUrl) {
            await axios.put(props.recordUrl, payload);
        } else {
            await axios.post(props.createUrl, payload);
        }
        notifySuccess(isTemplate.value
            ? $gettext('Hour template saved. Wheels made from it were updated.')
            : $gettext('Clock Wheel saved.'));
        emit('saved');
    }, $gettext('Could not save this %{noun}.', {noun: noun.value}));
};

const doDuplicate = async () => {
    const payload = buildPayload();
    if (!payload) {
        return;
    }
    await run(async () => {
        await axios.post(props.createUrl, {
            ...payload,
            name: $gettext('%{name} Copy', {name: form.value.name}),
            is_active: false,
            inherits_template_slots: false,
        });
        notifySuccess($gettext('Clock Wheel duplicated as an inactive copy.'));
        emit('saved');
    }, $gettext('Could not duplicate this clock wheel.'));
};

const doDelete = async () => {
    if (!props.recordUrl) {
        return;
    }
    const {value} = await confirmDelete({title: $gettext('Delete “%{name}”?', {name: form.value.name})});
    if (!value) {
        return;
    }
    await run(async () => {
        await axios.delete(props.recordUrl as string);
        notifySuccess(isTemplate.value ? $gettext('Hour template deleted.') : $gettext('Clock Wheel deleted.'));
        emit('saved');
    }, isTemplate.value
        ? $gettext('Could not delete this hour template. Remove the dayparts that use it first.')
        : $gettext('Could not delete this clock wheel.'));
};
</script>

<style scoped>
.proposal-list {
    max-height: 14rem;
    overflow-y: auto;
    columns: 2;
}

.legend-dot {
    display: inline-block;
    width: .7rem;
    height: .7rem;
    border-radius: 50%;
}

.type-bar {
    display: inline-block;
    width: .4rem;
    height: 1.6rem;
    border-radius: .2rem;
    vertical-align: middle;
}

.drag-handle {
    cursor: grab;
}

.slot-table tbody tr {
    cursor: pointer;
}
</style>
