<template>
    <tab :label="$gettext('Basic Info')">
        <div class="mb-3">
            <form-group-field
                id="name"
                :field="r$.name"
                :label="$gettext('Title')"
            />
        </div>

        <div class="mb-3">
            <label class="form-label fw-semibold">{{ $gettext('Color') }} *</label>
            <div>
                <input
                    id="color"
                    v-model="form.color"
                    type="color"
                    style="width: 3rem; height: 3rem; padding: 0.15rem; border: 2px solid #555; border-radius: 6px; cursor: pointer; background: none;"
                />
            </div>
        </div>

        <form-group-checkbox
            v-if="!isTemplate"
            id="is_active"
            class="mb-3"
            :field="r$.is_active"
            :label="$gettext('Active')"
            :description="$gettext('Inactive wheels are saved but do not run on-air until scheduled on the station Schedule page.')"
        />

        <form-group-select
            v-if="!isTemplate"
            id="fill_strategy"
            class="mb-3"
            :field="r$.fill_strategy"
            :label="$gettext('Fill strategy')"
            :description="$gettext('Conservative skips tight windows in preview; aggressive picks the shortest fitting track.')"
            :options="fillStrategyOptions"
        />

        <form-group-checkbox
            id="separation_enabled"
            class="mb-3"
            :field="r$.separation_enabled"
            :label="$gettext('Enable separation rules')"
            :description="isTemplate
                ? $gettext('Default rules for wheels linked to this template when the wheel has no separation enabled.')
                : $gettext('Apply artist/title/time windows and optional burn-rate limits when queueing from this wheel. Slots with a category also avoid repeating that category within the artist window.')"
        />

        <template v-if="!isTemplate && isDaypartManaged">
            <div class="alert alert-secondary py-2 mb-3">
                {{ $gettext('This wheel was generated by a daypart. Its template link and slots are updated when you save or re-sync that daypart.') }}
            </div>
        </template>

        <template v-else-if="!isTemplate && templateOptions.length > 0">
            <form-group-select
                id="clock_wheel_template"
                class="mb-3"
                :field="r$.template_id"
                :label="$gettext('Clock template')"
                :options="templateSelectOptions"
                :description="$gettext('Optional. Link this wheel to a reusable template layout.')"
            />

            <form-group-checkbox
                id="inherits_template_slots"
                class="mb-3"
                :field="r$.inherits_template_slots"
                :label="$gettext('Inherit template slots')"
                :description="$gettext('When enabled, slot layout is copied from the template and updates when the template changes. Disable to edit slots on this wheel only.')"
                :disabled="!form.template_id"
            />
        </template>

        <div
            v-if="form.separation_enabled"
            class="row mb-3"
        >
            <div class="col-md-4">
                <form-group-field
                    id="separation_artist_minutes"
                    :field="r$.separation_artist_minutes"
                    :label="$gettext('Artist separation (min)')"
                    type="number"
                />
            </div>
            <div class="col-md-4">
                <form-group-field
                    id="separation_title_minutes"
                    :field="r$.separation_title_minutes"
                    :label="$gettext('Title separation (min)')"
                    type="number"
                />
            </div>
            <div class="col-md-4">
                <form-group-field
                    id="burn_rate_max_plays_24h"
                    :field="r$.burn_rate_max_plays_24h"
                    :label="$gettext('Max plays / 24h')"
                    type="number"
                    :description="$gettext('Leave empty to disable burn-rate deprioritization.')"
                />
            </div>
        </div>

        <div
            v-if="!isTemplate"
            class="alert alert-info py-2 mb-4"
        >
            {{ $gettext('Air times are managed on the station Schedule page (calendar), not here. Create the wheel first, then use Schedule → Create Event to assign it.') }}
        </div>

        <div
            v-if="!isTemplate && slotsReadOnly"
            class="alert alert-warning py-2 mb-3"
        >
            {{ $gettext('Slots are managed by the linked template. Turn off “Inherit template slots” to edit this wheel’s layout locally.') }}
        </div>

        <div
            class="mb-1"
            :class="{'opacity-50 pe-none': slotsReadOnly}"
        >
            <div class="d-flex align-items-center justify-content-between mb-2">
                <span class="fw-semibold">
                    {{ $gettext('Clockwheel entries') }} ({{ entries.length }})
                </span>
            </div>

            <div
                v-if="entries.length > 0"
                class="clock-wheel-hour-distribution mb-3"
            >
                <div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-1">
                    <span class="fw-semibold small">{{ $gettext('Hour distribution') }}</span>
                    <div class="d-flex align-items-center gap-2">
                        <span
                            class="badge"
                            :class="layoutValid ? 'text-bg-success' : 'text-bg-warning'"
                        >
                            {{ layoutValid ? $gettext('Valid layout') : $gettext('Needs review') }}
                        </span>
                        <span class="small text-muted">
                            {{ $gettext('Est. loop') }}: {{ formatLoopTime(estimatedLoopSeconds) }}
                        </span>
                    </div>
                </div>
                <div
                    class="clock-wheel-hour-distribution__bars d-flex gap-1 align-items-end"
                    role="img"
                    :aria-label="$gettext('Anchor density across the hour')"
                >
                    <div
                        v-for="bucket in hourDistribution"
                        :key="bucket.segment"
                        class="clock-wheel-hour-distribution__bar flex-grow-1 rounded-top"
                        :style="{ height: barHeight(bucket.count) + 'px' }"
                        :title="bucket.label + ': ' + bucket.count"
                    />
                </div>
            </div>

            <div
                v-if="entries.length > 0"
                class="clock-wheel-timeline mb-3"
                role="img"
                :aria-label="$gettext('Hour timeline showing anchor positions')"
            >
                <div class="clock-wheel-timeline__track">
                    <span class="clock-wheel-timeline__label clock-wheel-timeline__label--start">0:00</span>
                    <span class="clock-wheel-timeline__label clock-wheel-timeline__label--end">59:59</span>
                    <button
                        v-for="(entry, index) in sortedEntries"
                        :key="'marker-' + index"
                        type="button"
                        class="clock-wheel-timeline__marker"
                        :style="{ left: timelinePercent(entry.position_seconds) + '%' }"
                        :title="formatPosition(entry.position_seconds) + ' — ' + slotLabel(entry)"
                        @click="focusRow(entries.indexOf(entry))"
                    />
                </div>
            </div>

            <div
                v-if="timelineWarnings.length > 0"
                class="alert alert-warning py-2 small mb-2"
            >
                <ul class="mb-0 ps-3">
                    <li
                        v-for="(warn, wi) in timelineWarnings"
                        :key="wi"
                    >
                        {{ formatPosition(entries[warn.index]?.position_seconds ?? 0) }}: {{ warn.message }}
                    </li>
                </ul>
            </div>

            <table class="table table-sm table-bordered mb-0 clock-wheel-entries-table">
                <thead>
                    <tr>
                        <th
                            class="text-uppercase small"
                            style="width: 2rem;"
                        />
                        <th class="text-uppercase small">
                            {{ $gettext('Position (m:s)') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Type') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Category') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Playlist') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Pool') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Algorithm') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Max sec') }}
                        </th>
                        <th
                            class="text-uppercase small text-center"
                            :title="$gettext('Hard anchor')"
                        >
                            {{ $gettext('Hard') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Score') }}
                        </th>
                        <th class="text-uppercase small">
                            {{ $gettext('Code') }}
                        </th>
                        <th
                            class="text-uppercase small text-center"
                            style="width: 9rem;"
                        >
                            {{ $gettext('Actions') }}
                        </th>
                    </tr>
                </thead>
                <tbody ref="$tbody">
                    <tr v-if="entries.length === 0">
                        <td
                            colspan="12"
                            class="text-center text-muted py-3"
                        >
                            {{ $gettext('No Clockwheel Entries found.') }}
                        </td>
                    </tr>
                    <tr
                        v-for="(entry, index) in entries"
                        :key="rowKey(entry, index)"
                        :class="{ 'table-warning': rowHasWarning(index) }"
                        :data-entry-index="index"
                    >
                        <td class="text-center align-middle drag-handle text-muted">
                            ⋮⋮
                        </td>
                        <td>
                            <input
                                :value="formatPosition(entry.position_seconds)"
                                type="text"
                                class="form-control form-control-sm"
                                placeholder="0:00"
                                @change="onPositionChange(entry, $event)"
                            >
                        </td>
                        <td>
                            <select
                                v-model="entry.type"
                                class="form-select form-select-sm"
                                required
                            >
                                <option
                                    v-for="opt in mediaTypeOptions"
                                    :key="opt.value"
                                    :value="opt.value"
                                >
                                    {{ opt.label }}
                                </option>
                            </select>
                        </td>
                        <td>
                            <select
                                v-model="entry.category_id"
                                class="form-select form-select-sm"
                                @change="props.onEntriesChanged()"
                            >
                                <option
                                    v-for="opt in categoryOptions"
                                    :key="String(opt.value)"
                                    :value="opt.value"
                                >
                                    {{ opt.text }}
                                </option>
                            </select>
                        </td>
                        <td>
                            <select
                                v-model="entry.playlist_id"
                                class="form-select form-select-sm"
                                @change="onPlaylistChange(entry)"
                            >
                                <option
                                    v-for="opt in playlistOptions"
                                    :key="String(opt.value)"
                                    :value="opt.value"
                                >
                                    {{ opt.text }}
                                </option>
                            </select>
                        </td>
                        <td>
                            <select
                                v-model="entry.pool_mode"
                                class="form-select form-select-sm"
                                :disabled="!entry.playlist_id"
                                :title="poolModeHelp"
                                @change="props.onEntriesChanged()"
                            >
                                <option value="restrict_pool">
                                    {{ $gettext('Restrict pool') }}
                                </option>
                                <option value="playlist_rotation">
                                    {{ $gettext('Run rotation rules') }}
                                </option>
                            </select>
                        </td>
                        <td>
                            <select
                                v-model="entry.algorithm"
                                class="form-select form-select-sm"
                                :disabled="entry.pool_mode === 'playlist_rotation' && !!entry.playlist_id"
                            >
                                <option value="random">
                                    {{ $gettext('Random') }}
                                </option>
                                <option value="sequential">
                                    {{ $gettext('Sequential (rotate evenly)') }}
                                </option>
                                <option value="oldest_album">
                                    {{ $gettext('Oldest Album') }}
                                </option>
                                <option value="oldest_artist">
                                    {{ $gettext('Oldest Artist') }}
                                </option>
                                <option value="oldest_track">
                                    {{ $gettext('Oldest Track') }}
                                </option>
                                <option value="most_recent_album">
                                    {{ $gettext('Most Recent Album') }}
                                </option>
                                <option value="most_recent_artist">
                                    {{ $gettext('Most Recent Artist') }}
                                </option>
                            </select>
                        </td>
                        <td>
                            <input
                                v-model.number="entry.duration_seconds"
                                type="number"
                                min="0"
                                max="3600"
                                class="form-control form-control-sm"
                                :placeholder="$gettext('Auto')"
                            >
                            <div
                                v-if="showSeparationOverrides"
                                class="mt-1"
                            >
                                <label class="form-check form-check-inline small mb-0">
                                    <input
                                        v-model="entry.separation_override_enabled"
                                        type="checkbox"
                                        class="form-check-input"
                                        @change="props.onEntriesChanged()"
                                    >
                                    {{ $gettext('Sep.') }}
                                </label>
                                <input
                                    v-if="entry.separation_override_enabled"
                                    v-model.number="entry.separation_artist_minutes"
                                    type="number"
                                    min="1"
                                    class="form-control form-control-sm mt-1"
                                    :placeholder="$gettext('Artist min')"
                                    @change="props.onEntriesChanged()"
                                >
                            </div>
                        </td>
                        <td class="text-center align-middle">
                            <input
                                v-model="entry.is_hard_anchor"
                                type="checkbox"
                                class="form-check-input"
                                :title="$gettext('Must play at this anchor time')"
                                @change="props.onEntriesChanged()"
                            >
                        </td>
                        <td>
                            <input
                                v-model.number="entry.research_score"
                                type="number"
                                min="0"
                                max="100"
                                class="form-control form-control-sm"
                                :placeholder="'—'"
                                @change="props.onEntriesChanged()"
                            >
                        </td>
                        <td>
                            <input
                                v-model="entry.sound_code"
                                type="text"
                                maxlength="20"
                                class="form-control form-control-sm"
                                :placeholder="'—'"
                                @change="props.onEntriesChanged()"
                            >
                        </td>
                        <td class="text-center align-middle">
                            <div class="btn-group btn-group-sm w-100 justify-content-center">
                                <button
                                    type="button"
                                    class="btn btn-outline-primary cw-action-btn"
                                    :title="$gettext('Insert after')"
                                    @click="props.insertEntryAfter(index)"
                                >
                                    <icon-ic-add />
                                </button>
                                <button
                                    type="button"
                                    class="btn btn-outline-secondary cw-action-btn"
                                    :title="$gettext('Duplicate')"
                                    @click="props.duplicateEntry(index)"
                                >
                                    <icon-ic-copy />
                                </button>
                                <button
                                    type="button"
                                    class="btn btn-outline-danger cw-action-btn"
                                    :title="$gettext('Delete')"
                                    @click="props.removeEntry(index)"
                                >
                                    <icon-ic-delete />
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>

            <button
                type="button"
                class="btn btn-outline-secondary btn-sm mb-2 me-2"
                @click="showSeparationOverrides = !showSeparationOverrides"
            >
                {{
                    showSeparationOverrides
                        ? $gettext('Hide per-slot separation')
                        : $gettext('Show per-slot separation')
                }}
            </button>

            <button
                type="button"
                class="btn btn-secondary w-100 mt-2"
                @click="props.addEntry()"
            >
                {{ $gettext('Add Clockwheel Entry') }}
            </button>
        </div>
    </tab>
</template>

<script setup lang="ts">
import FormGroupField from '~/components/Form/FormGroupField.vue';
import FormGroupCheckbox from '~/components/Form/FormGroupCheckbox.vue';
import FormGroupSelect from '~/components/Form/FormGroupSelect.vue';
import Tab from '~/components/Common/Tab.vue';
import {computed, onMounted, ref, useTemplateRef} from 'vue';
import {useTranslate} from '~/vendor/gettext';
import {useDraggable} from 'vue-draggable-plus';
import {useClockWheelSlotOptions} from '~/functions/useClockWheelSlotOptions.ts';
import IconIcDelete from '~icons/ic/baseline-delete';
import IconIcAdd from '~icons/ic/baseline-add';
import IconIcCopy from '~icons/ic/baseline-content-copy';
import {
    formatClockWheelPosition,
    getClockWheelTimelineWarnings,
    getClockWheelHourDistribution,
    estimateClockWheelLoopSeconds,
    isClockWheelLayoutValid,
    parseClockWheelPosition,
    timelinePercent,
} from '~/functions/clockWheelPosition.ts';
import {formatMediaType, getMediaTypeOptions, type MediaTypeValue} from '~/functions/mediaTypes.ts';

const {$gettext} = useTranslate();

const {categoryOptions, playlistOptions, load: loadSlotOptions} = useClockWheelSlotOptions();
const showSeparationOverrides = ref(false);

const poolModeHelp = computed(() =>
    $gettext('Restrict pool: filter by playlist then use slot algorithm. Run rotation rules: follow the playlist AutoDJ order.')
);

export interface ClockWheelEntryRow {
    type: MediaTypeValue;
    algorithm: string;
    position_seconds: number;
    duration_seconds: number | null;
    category_id: number | null;
    playlist_id: number | null;
    pool_mode: 'restrict_pool' | 'playlist_rotation';
    separation_override_enabled: boolean;
    separation_artist_minutes: number | null;
    separation_title_minutes: number | null;
    is_hard_anchor: boolean;
    research_score: number | null;
    sound_code: string | null;
}

const fillStrategyOptions = computed(() => [
    {value: 'conservative', text: $gettext('Conservative (defer tight windows)')},
    {value: 'aggressive', text: $gettext('Aggressive (shortest fit)')},
]);

const props = withDefaults(defineProps<{
    variant?: 'wheel' | 'template';
    form: {
        name: string;
        color: string;
        is_active?: boolean;
        fill_strategy?: string;
        separation_enabled?: boolean;
        separation_artist_minutes?: number;
        separation_title_minutes?: number;
        burn_rate_max_plays_24h?: number | null;
        template_id?: number | null;
        inherits_template_slots?: boolean;
        daypart_id?: number | null;
    };
    r$: {
        name: {required: unknown};
        color: object;
        is_active?: object;
        fill_strategy?: object;
        separation_enabled?: object;
        separation_artist_minutes?: object;
        separation_title_minutes?: object;
        burn_rate_max_plays_24h?: object;
        template_id?: object;
        inherits_template_slots?: object;
    };
    templateOptions?: {value: number; text: string}[];
    addEntry: () => void;
    removeEntry: (index: number) => void;
    duplicateEntry: (index: number) => void;
    insertEntryAfter: (index: number) => void;
    onEntriesReordered: () => void;
    onEntriesChanged: () => void;
}>(), {
    variant: 'wheel',
    templateOptions: () => [],
});

const isTemplate = computed(() => props.variant === 'template');

const isDaypartManaged = computed(() =>
    !isTemplate.value && props.form.daypart_id != null && props.form.daypart_id > 0
);

const slotsReadOnly = computed(() => {
    if (isTemplate.value) {
        return false;
    }

    if (isDaypartManaged.value) {
        return true;
    }

    return Boolean(props.form.inherits_template_slots)
        && props.form.template_id != null;
});

const templateSelectOptions = computed(() => [
    {value: null as unknown as number, text: $gettext('— None —')},
    ...props.templateOptions,
]);

// IMPORTANT: Use a v-model ref so drag-reorder can mutate the array.
const entries = defineModel<ClockWheelEntryRow[]>('entries', {required: true});

const mediaTypeOptions = computed(() => getMediaTypeOptions($gettext));

const sortedEntries = computed(() =>
    [...entries.value].sort((a, b) => a.position_seconds - b.position_seconds)
);

const timelineWarnings = computed(() =>
    getClockWheelTimelineWarnings(entries.value, $gettext)
);

const hourDistribution = computed(() => getClockWheelHourDistribution(entries.value));

const estimatedLoopSeconds = computed(() =>
    estimateClockWheelLoopSeconds(entries.value)
);

const layoutValid = computed(() => isClockWheelLayoutValid(entries.value));

const maxBucketCount = computed(() =>
    Math.max(1, ...hourDistribution.value.map((b) => b.count))
);

const barHeight = (count: number) =>
    count === 0 ? 2 : Math.max(4, Math.round((count / maxBucketCount.value) * 28));

const formatLoopTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${String(secs).padStart(2, '0')}`;
};

const $tbody = useTemplateRef('$tbody');

onMounted(() => {
    void loadSlotOptions();

    if ($tbody.value === null) {
        return;
    }

    useDraggable($tbody.value, entries, {
        handle: '.drag-handle',
        animation: 150,
        onEnd() {
            props.onEntriesReordered();
        },
    });
});

const formatPosition = formatClockWheelPosition;
const slotLabel = (entry: ClockWheelEntryRow) => formatMediaType(entry.type, $gettext);

const rowKey = (entry: ClockWheelEntryRow, index: number) =>
    `${index}-${entry.position_seconds}-${entry.type}`;

const rowHasWarning = (index: number) =>
    timelineWarnings.value.some((w) => w.index === index);

const onPositionChange = (entry: ClockWheelEntryRow, event: Event) => {
    const target = event.target as HTMLInputElement;
    entry.position_seconds = parseClockWheelPosition(target.value);
    target.value = formatPosition(entry.position_seconds);
    props.onEntriesChanged();
};

const onPlaylistChange = (entry: ClockWheelEntryRow) => {
    if (!entry.playlist_id) {
        entry.pool_mode = 'restrict_pool';
    }
    props.onEntriesChanged();
};

const focusRow = (index: number) => {
    if (index < 0) {
        return;
    }
    const row = $tbody.value?.querySelector(`tr[data-entry-index="${index}"]`);
    row?.scrollIntoView({behavior: 'smooth', block: 'nearest'});
};
</script>

<style lang="scss" scoped>
.clock-wheel-timeline__track {
    position: relative;
    height: 2rem;
    background: var(--bs-secondary-bg);
    border: 1px solid var(--bs-border-color);
    border-radius: 0.375rem;
}

.clock-wheel-timeline__label {
    position: absolute;
    top: 100%;
    font-size: 0.65rem;
    color: var(--bs-secondary-color);
    margin-top: 0.15rem;

    &--start {
        left: 0;
    }

    &--end {
        right: 0;
    }
}

.clock-wheel-timeline__marker {
    position: absolute;
    top: 50%;
    width: 0.65rem;
    height: 1.25rem;
    margin: 0;
    padding: 0;
    border: none;
    border-radius: 2px;
    background: var(--bs-primary);
    transform: translate(-50%, -50%);
    cursor: pointer;
    opacity: 0.85;

    &:hover,
    &:focus {
        opacity: 1;
        outline: 2px solid var(--bs-primary);
        outline-offset: 2px;
    }
}

.clock-wheel-entries-table.sortable,
.clock-wheel-entries-table .drag-handle {
    cursor: grab;
}

.clock-wheel-entries-table .drag-handle:active {
    cursor: grabbing;
}

.cw-action-btn {
    width: 2.25rem;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding-left: 0;
    padding-right: 0;
}

.clock-wheel-hour-distribution__bars {
    min-height: 2rem;
    padding: 0.25rem 0;
    border-bottom: 1px solid var(--bs-border-color);
}

.clock-wheel-hour-distribution__bar {
    min-width: 3px;
    background: var(--bs-primary);
    opacity: 0.75;
}
</style>
