name: Build Custom AzuraCast
on:
  push:
    branches: [ main, dev ]
    tags: [ 'v*' ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Version File
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "${{ github.ref_name }}" > .version
          else
            echo "$(git rev-parse --short HEAD)" > .version
          fi
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/eternityready2/azuracast_custom:${{ github.ref_name == 'main' && 'latest' || 'rolling' }}
            ${{ github.ref_name == 'main' && 'ghcr.io/eternityready2/azuracast_custom:stable' || '' }}